name: "Docker Build action"
description: "Docker build"
inputs:
  branch:
    description: "The branch name"
    required: true

  binary_path:
    description: "Binary path"
    required: true

  image_name:
    description: "The name of the image"
    required: true

  registry_endpoint:
    description: "Registry base url (ie: eu.gcr.io)"
    required: true

  registry_name:
    description: "Name of the registry storing the image"
    required: true

  registry_username:
    description: "Username used to login to the registry"
    required: true

  registry_password:
    description: "Password used to login to the registry"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
