name: "Docker Build action"
description: "Docker build"
inputs:
  branch:
    description: "The branch name"
    required: true

  image_name:
    description: "The name of the image"
    required: true

  registry_endpoint:
    description: "Registry base url (ie: eu.gcr.io)"
    required: true

  registry_name:
    description: "Name of the registry storing the image"
    required: true

  registry_username:
    description: "Username used to login to the registry"
    required: true

  registry_password:
    description: "Password used to login to the registry"
    required: true

  dockerfile:
    description: "Path to the dockerfile to be built"
    required: true
    default: ./docker/Dockerfile

  dockerfile_target:
    description: "The dockerfile target build stage to build"
    required: false
    default: ""

  docker_build_args:
    description: "Extra arguments to add to docker build command"
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
